default:
  tags:
    - linux

stages:
  - prepare
  - lint
  - test

build_build_image:
  services:
    - docker:24-dind
  image: docker:24-cli
  stage: prepare
  before_script:
    # this is to be able to pull and push images
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - cd .ci
    - docker build -t $CI_REGISTRY_IMAGE/buildimage:latest .
    - docker push $CI_REGISTRY_IMAGE/buildimage:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE != "push"'
      when: never
    - changes:
        - .ci/Dockerfile

lint:
  image: $CI_REGISTRY_IMAGE/buildimage:latest
  stage: lint
  before_script: deno install --frozen
  script:
    - SKIP='prettier' pre-commit run --all-files
    - deno task format:check
    - deno task lint
    - deno audit --socket
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
    DENO_DIR: ${CI_PROJECT_DIR}/.cache/deno
  cache:
    - key:
        files:
          - deno.lock
      paths:
        - .cache/deno

test:
  image: $CI_REGISTRY_IMAGE/buildimage:latest
  stage: test
  before_script: deno install --frozen
  script: deno task test:ci
  coverage: /All files(?:[^|]*\|){4}\s*(\S+)/
  artifacts:
    expire_in: 1 week
    paths:
      - coverage/
    when: always
    reports:
      junit:
        - junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
  variables:
    DENO_DIR: ${CI_PROJECT_DIR}/.cache/deno
  cache:
    - key:
        files:
          - deno.lock
      paths:
        - .cache/deno
